#!/usr/bin/env zsh
#
# If invoked with an argument, passes unrecognized TTY content to zle.

local fd=${_z4h_tty_fd-1}
[[ -t $fd ]] || return

# Use a /dev/fd path instead of a dynamic descriptor redirect so this helper
# remains compatible with zsh's `-n` syntax checks while still talking to the
# same tty descriptor at runtime.
local tty=/dev/fd/$fd

local resp
print -rn -- $'\e[6n' >$tty || return
IFS= builtin read -srt 5 -d R resp <$tty || return

while [[ $resp != *$'\e['<->';'<-> ]]; do
  IFS= builtin read -srt 5 -d R resp <$tty || return
done

if (( ARGC )); then
  local pref=${resp%$'\e['*}
  [[ -n $pref ]] && print -rz -- $pref
fi

resp=${resp##*'['}
typeset -g cursor_y=${resp%';'*}
typeset -g cursor_x=${resp#*';'}
